version: "3"
 
services:
  mysql:
    image: darroyote/mysql_for_rtb:v1
    # Exponemos las variables
    network_mode: bridge
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      - MYSQL_USER=root
      - MYSQL_ALLOW_EMPTY_PASSWORD=False
      - MYSQL_DATABASE=db
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_root_host=%
      - DB_HOST=mysql  
      - MYSQL_PASSWORD=password
    volumes:
      # Persistencia de datos
      - ./db-data:/var/lib/mysql
    expose:
      - 3306
    ports:
      - "3306:3306"
  myrtb:
    image: darroyote/myrtb:v1
    network_mode: bridge
    links: 
      - mysql     
    environment:
      - MYSQL_USER=root
      - MYSQL_ALLOW_EMPTY_PASSWORD=False
      - MYSQL_DATABASE=db
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_root_host=%
      - DB_HOST=mysql
      - MYSQL_PASSWORD=password
    volumes:
      # Montamos nuestra web desde fuera en el directorio web del contenedor
      - ./db-data:/myrtb/
    expose:
      - 8080
    ports:
      - "8080:8080"
       
